### ISSUE TITLE
Wouldn't it be much simpler to require the preset instead of providing its name?

### ISSUE THREAD

**Issue by julien-f** [developit/modify-babel-preset#4] opened 2016-03-18 13:52 UTC
``` js
const newPreset = modifyBabelPreset(require('babel-preset-stage-0'), {
  'transform-async-to-generator': false,
  'kneden': true
})
```

Also it would be nice if this lib could be used as a Babel plugin and configured in `.babelrc`, not sure if it's feasible though.

**Comment by developit** [comment] 2016-03-18 13:54
The issue is with relative module paths - by requiring the preset, there is no way to figure out its name.
Next version of this module is going to support specifying a full file path so it's more obvious what is going on.

As for the babel plugin, the simplest method is to create derivative plugins and publish them to npm:
https://github.com/bkonkle/babel-preset-es2015-loose
https://github.com/developit/babel-preset-es2015-minimal

**Comment by julien-f** [comment] 2016-03-25 14:45
Yes, but it would be nice to be able to do it directly in `.babelrc`:

``` json
{
  "plugins": [
    [ "modify-babel-preset", [ "stage-0", {
      "transform-async-to-generator": false,
      "kneden": true
    } ] ]
  ]
}
```

**Comment by developit** [comment] 2016-03-25 16:08
@julien-f ooh, that's an awesome idea. I can make this work with v2, it does a recursive name search in Node_modules

**Comment by developit** [comment] 2016-04-06 20:20
@julien-f I looked into this and it appears to be impossible :(

**Comment by julien-f** [comment] 2016-04-08 08:42
What's the problem?

**Comment by developit** [comment] 2016-04-08 13:26
The plugin would return an Array of plugins, but Babel only supports flat plugin lists or nesting via presets.

This might be an option, but I've never seen it used as such and I'm not sure if it's supported:

``` js
{
  "presets": [
    [ "modify-babel-preset", [ "stage-0", {
      "transform-async-to-generator": false,
      "kneden": true
    } ] ]
  ]
}
```

**Comment by julien-f** [comment] 2016-04-08 13:27
@loganfsmyth Any pointers?

**Comment by loganfsmyth** [comment] 2016-04-08 16:23
We want to support options for presets too to support cases like this, we haven't come to a firm decision on the best next step for the APIs yet though.

**Comment by developit** [comment] 2016-04-08 16:25
@loganfsmyth good to hear. Is there an issue where this is being looked into? babel-preset-es2015-loose is quite popular and is using this module, so it seems wise to keep abreast of any upcoming opportunities to simplify things.

**Comment by loganfsmyth** [comment] 2016-04-08 16:35
https://phabricator.babeljs.io/T2756 is the issue that we've used to track it. I'll update it with links now.

**Comment by developit** [comment] 2016-08-13 17:52
I think we can close this out now that Babel itself supports preset options.

**Closed as completed by developit** 2016-08-13 17:52 UTC
Labels: enhancement, help wanted
